### ISSUE TITLE
Getting issue when I am adding items to Cart

### ISSUE THREAD

**Issue by sahiliotasol** [moltin/js-sdk#27] opened 2016-02-05 08:11 UTC
Using Moltin js sdk.
I am adding Items to cart but when i checkout
I see that the items which are added are not same
sometimes it is from last order
and sometimes in existing order any one of item is randomly missing
this is really strange behaviour
I am also deleting the cart when the payment is successful
can you please tell me why it is happening so?

Here is the code which I am using-

 
var _addItemToCart = function(product, qty){
      moltin.Cart.Insert(product.id, qty, null,function(obj){
        console.log("Return of cart item :");
        console.log(obj);
      });
    };

    var _processOrder = function(obj,invoiceData){
      var user = obj.user;
      
      var order = moltin.Cart.Complete({
        gateway: 'paypal-express',
        customer: {
          first_name: user.name,
          last_name:  user.surname,
          email:      user.email
        },
        bill_to: {
          first_name: user.name,
          last_name:  user.surname,
          address_1:  invoiceData.clientCompanyAddress,
          city:       invoiceData.clientCompanyCity,
          county:     invoiceData.clientCompanyProvince,
          country:    invoiceData.clientCompanyCountry,
          postcode:   invoiceData.clientCompanyPostalCode
        },
        ship_to: 'bill_to',
        shipping: 'free_shipping'
      });
       
       console.log("orderId");
       console.log(order.id);

      var checkout = moltin.Checkout.Payment('purchase', order.id, {
        return_url: siteBasicUrl + FF_CONFIG.call.shopping.paypalSuccessRedirectUrl.path + '?orderId='+order.id,
        cancel_url: siteBasicUrl + FF_CONFIG.call.shopping.paypalCancelRedirectUrl.path + '?orderId='+order.id,
        data: {
          /*number:       '4242424242424242',
          expiry_month: '02',
          expiry_year:  '2017',
          cvv:          '123'*/
        }
      },function(success){
        console.log('success');
        console.log(success);
        moltin.Cart.Delete();
        window.location.href = success.url;
      });
    };

**Comment by AndreaPravato** [comment] 2016-02-05 08:17
Hi! This is a serious and priority issue for us. 
In front-end side, we are adding products to cart, doing the checkout and then passing the orderid to Backend. Backend calls Moltin passing the orderId and so it finds out which products are purchased. 
The Problem is that Backend receives from Moltin a list of products that is not the same as the ones that were purchased in the Front-end.

**Comment by AndreaPravato** [comment] 2016-02-05 13:42
Sahil temporarily solved it adding items to the cart through recursion

**Comment by AndreaPravato** [comment] 2016-02-11 13:17
This can be closed as it is now solved by Moltin

**Closed** 2016-02-11 13:20 UTC
