### ISSUE TITLE
Can't import moltin using es6

### ISSUE THREAD

**Issue by eashish93** [moltin/js-sdk#68] opened 2017-05-01 13:59 UTC
Hi,
I can't be able to import moltin in react using es6. I got the following error:
`Uncaught TypeError: (0 , _moltin.gateway) is not a function`

```
 // this doesn't work
import {gateway as MoltinGateway} from 'moltin'; 
```

It because I think you've not provided any `index.js` file in `src` folder.

The only way to make it work using dist folder:
```
// It worked
import {gateway as MoltinGateway} from 'moltin/dist/moltin.cjs.js';

``` 

Please add the `index.js` file in **src** folder.

**Comment by ynnoj** [comment] 2017-05-02 09:03
@eashish93 Are you using `webpack` in your project?

The issue is the entry point defined in `package.json`. I'll be publishing a new release today which _should_ fix this issue. I'm working with the `master` branch of the library locally in a Vue.js store (with webpack configuration).

**Comment by eashish93** [comment] 2017-05-02 09:40
also, the sdk doesn't have a method for querying things like `products?page[limit]=10`.

**Comment by ynnoj** [comment] 2017-05-02 09:41
@eashish93 We're still working to bring all API functionality to the SDK.

**Comment by eashish93** [comment] 2017-05-02 09:44
Currently I'm also using master branch with slight modifications to support querying like this: 
```js
export default class Collections {
    constructor(config) {
        this.config = config;
        this.request = new Request(config);
    }

    Tree(qs) { 
      // where qs  is a string with things like: `page[limit]=10`.
        return this.request.send(`collections?${qs}`, 'GET');
    }

}

```

**Comment by ynnoj** [comment] 2017-05-02 09:48
@eashish93 Filtering, sorting and pagination will be separate methods which will be chained. For example:

```js
Moltin.Products.Sort('name').Limit(10).Offset(20).All()
```

**Comment by eashish93** [comment] 2017-05-02 10:42
I've read the code. There's no such method in any files in master branch currently.

**Comment by ynnoj** [comment] 2017-05-02 10:54
> We're still working to bring all API functionality to the SDK.

@eashish93 As I said above ☝️ 🙃

**Comment by ynnoj** [comment] 2017-05-02 11:19
@eashish93 Are you able to import the library now via the master branch? I'll go ahead and close this issue.

**Comment by eashish93** [comment] 2017-05-02 11:25
yes, but not as given in the doc. 
It should be: 
```
import {moltin} from 'moltin';
const Moltin = motin.gateway({
client_id: 'xxxx'
});

```

**Comment by ynnoj** [comment] 2017-05-02 11:34
@eashish93 How is your project setup? Are you using Webpack?

**Comment by eashish93** [comment] 2017-05-02 11:37
I'm using webpack with facebook create-react-app.

**Comment by nclsmitchell** [comment] 2017-05-06 22:51
Hi @eashish93 ,

I encountered the same problem as you, I fixed it by using the following:

`import {gateway as MoltinGateway} from 'moltin'`

and then:

```
const Moltin = MoltinGateway({
    client_id: 'XXXX',
})
```

The syntax `client_id` is the key ;)

**Closed** 2017-05-08 20:19 UTC
